package Tugas2;


import javax.swing.Icon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HeryAdityaa
 */
public class Tugas2_Output extends javax.swing.JFrame {

    /**
     * Creates new form Tugas2_Output
     */
    public Tugas2_Output() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public Tugas2_Output(String Nama, String ttl, String tl, String JK, String Alamat, String RT, String RW, String desa, String Kec, String kota, String agama,String status, String godar,String pekerjaan,String kewarganegaraan)
         {
        initComponents();
        namanyaa.setText(Nama);
        tempanyaa.setText(ttl);
        tanggalnyaa.setText(tl);
        jknya.setText(""+JK);
        alamatnyaa.setText(Alamat);
        rtnyaa.setText(RT);
        rwnyaa.setText(RW);
        desanyaa.setText(desa);
        kecamatannyaa.setText(Kec);
        kotanyaa.setText(kota);
        agamanyaa.setText(""+agama);
        statusnyaa.setText(""+status);
        darahnyaa.setText(""+godar);
        pekerjaannyaa.setText(pekerjaan);
        kewarganegaraannya.setText(""+kewarganegaraan);
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        ttl2 = new javax.swing.JLabel();
        jk2 = new javax.swing.JLabel();
        almt2 = new javax.swing.JLabel();
        rr2 = new javax.swing.JLabel();
        kd2 = new javax.swing.JLabel();
        kec2 = new javax.swing.JLabel();
        kota2 = new javax.swing.JLabel();
        agm2 = new javax.swing.JLabel();
        sts2 = new javax.swing.JLabel();
        gd2 = new javax.swing.JLabel();
        pk2 = new javax.swing.JLabel();
        kw2 = new javax.swing.JLabel();
        namanyaa = new javax.swing.JTextField();
        tempanyaa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tanggalnyaa = new javax.swing.JTextField();
        alamatnyaa = new javax.swing.JTextField();
        rtnyaa = new javax.swing.JTextField();
        rwnyaa = new javax.swing.JTextField();
        desanyaa = new javax.swing.JTextField();
        kecamatannyaa = new javax.swing.JTextField();
        kotanyaa = new javax.swing.JTextField();
        pekerjaannyaa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        kewarganegaraannya = new javax.swing.JTextField();
        darahnyaa = new javax.swing.JTextField();
        agamanyaa = new javax.swing.JTextField();
        statusnyaa = new javax.swing.JTextField();
        jknya = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        nama.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama.setText("Nama");

        ttl2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ttl2.setText("Tempat/Tanggal Lahir");

        jk2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jk2.setText("Jenis Kelamin");

        almt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        almt2.setText("Alamat");

        rr2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rr2.setText("RT/RW");

        kd2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kd2.setText("Kel/Desa");

        kec2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kec2.setText("Kecamatan");

        kota2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kota2.setText("Kota");

        agm2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        agm2.setText("Agama");

        sts2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sts2.setText("Status");

        gd2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gd2.setText("Golongan Darah");

        pk2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pk2.setText("Pekerjaan");

        kw2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kw2.setText("Kewarganeraan");

        namanyaa.setEditable(false);

        tempanyaa.setEditable(false);

        jLabel15.setText("/");

        tanggalnyaa.setEditable(false);

        alamatnyaa.setEditable(false);

        rtnyaa.setEditable(false);

        rwnyaa.setEditable(false);

        desanyaa.setEditable(false);

        kecamatannyaa.setEditable(false);
        kecamatannyaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kecamatannyaaActionPerformed(evt);
            }
        });

        kotanyaa.setEditable(false);

        pekerjaannyaa.setEditable(false);

        jLabel16.setText("/");

        kewarganegaraannya.setEditable(false);

        darahnyaa.setEditable(false);

        agamanyaa.setEditable(false);

        statusnyaa.setEditable(false);

        jknya.setEditable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 2, 24)); // NOI18N
        jLabel1.setText("KARTU TANDA PENDUDUK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama)
                            .addComponent(ttl2)
                            .addComponent(jk2)
                            .addComponent(almt2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kd2)
                                    .addComponent(rr2)
                                    .addComponent(kec2)
                                    .addComponent(kota2)))
                            .addComponent(agm2)
                            .addComponent(sts2)
                            .addComponent(gd2)
                            .addComponent(pk2)
                            .addComponent(kw2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namanyaa)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tempanyaa, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tanggalnyaa, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                            .addComponent(alamatnyaa)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rtnyaa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rwnyaa))
                            .addComponent(desanyaa)
                            .addComponent(kecamatannyaa)
                            .addComponent(kotanyaa)
                            .addComponent(pekerjaannyaa)
                            .addComponent(kewarganegaraannya, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(darahnyaa)
                            .addComponent(agamanyaa)
                            .addComponent(statusnyaa)
                            .addComponent(jknya)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama)
                    .addComponent(namanyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempanyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ttl2)
                        .addComponent(jLabel15)
                        .addComponent(tanggalnyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jk2)
                    .addComponent(jknya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(almt2)
                    .addComponent(alamatnyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rr2)
                    .addComponent(rtnyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rwnyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kd2)
                    .addComponent(desanyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kec2)
                    .addComponent(kecamatannyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kota2)
                    .addComponent(kotanyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agm2)
                    .addComponent(agamanyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sts2)
                    .addComponent(statusnyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gd2)
                    .addComponent(darahnyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pk2)
                    .addComponent(pekerjaannyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kw2)
                    .addComponent(kewarganegaraannya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void kecamatannyaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kecamatannyaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kecamatannyaaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas2_Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas2_Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas2_Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas2_Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas2_Output().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agamanyaa;
    private javax.swing.JLabel agm2;
    private javax.swing.JTextField alamatnyaa;
    private javax.swing.JLabel almt2;
    private javax.swing.JTextField darahnyaa;
    private javax.swing.JTextField desanyaa;
    private javax.swing.JLabel gd2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jk2;
    private javax.swing.JTextField jknya;
    private javax.swing.JLabel kd2;
    private javax.swing.JLabel kec2;
    private javax.swing.JTextField kecamatannyaa;
    private javax.swing.JTextField kewarganegaraannya;
    private javax.swing.JLabel kota2;
    private javax.swing.JTextField kotanyaa;
    private javax.swing.JLabel kw2;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField namanyaa;
    private javax.swing.JTextField pekerjaannyaa;
    private javax.swing.JLabel pk2;
    private javax.swing.JLabel rr2;
    private javax.swing.JTextField rtnyaa;
    private javax.swing.JTextField rwnyaa;
    private javax.swing.JTextField statusnyaa;
    private javax.swing.JLabel sts2;
    private javax.swing.JTextField tanggalnyaa;
    private javax.swing.JTextField tempanyaa;
    private javax.swing.JLabel ttl2;
    // End of variables declaration//GEN-END:variables
}
