package Tugas2;


import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HeryAdityaa
 */
public class Tugas2 extends javax.swing.JFrame {

   
    public Tugas2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        ttl = new javax.swing.JLabel();
        jk = new javax.swing.JLabel();
        almt = new javax.swing.JLabel();
        rtrw = new javax.swing.JLabel();
        kd = new javax.swing.JLabel();
        kec = new javax.swing.JLabel();
        kota = new javax.swing.JLabel();
        agm = new javax.swing.JLabel();
        sts = new javax.swing.JLabel();
        gd = new javax.swing.JLabel();
        pk = new javax.swing.JLabel();
        kw = new javax.swing.JLabel();
        namanya = new javax.swing.JTextField();
        tempatnya = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tanggalnya = new javax.swing.JTextField();
        laki = new javax.swing.JRadioButton();
        bini = new javax.swing.JRadioButton();
        alamatnya = new javax.swing.JTextField();
        rtnya = new javax.swing.JTextField();
        rwnya = new javax.swing.JTextField();
        desanya = new javax.swing.JTextField();
        kecamatannya = new javax.swing.JTextField();
        kotanya = new javax.swing.JTextField();
        pilihan = new javax.swing.JComboBox<String>();
        statusnya = new javax.swing.JComboBox<String>();
        darah = new javax.swing.JComboBox<String>();
        pekerjaanya = new javax.swing.JTextField();
        wni = new javax.swing.JRadioButton();
        wna = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        register = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        nama.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama.setText("Nama");

        ttl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ttl.setText("Tempat/Tanggal Lahir");

        jk.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jk.setText("Jenis Kelamin");

        almt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        almt.setText("Alamat");

        rtrw.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rtrw.setText("RT/RW");

        kd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kd.setText("Kel/Desa");

        kec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kec.setText("Kecamatan");

        kota.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kota.setText("Kota");

        agm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        agm.setText("Agama");

        sts.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sts.setText("Status");

        gd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gd.setText("Golongan Darah");

        pk.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pk.setText("Pekerjaan");

        kw.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kw.setText("Kewarganeraan");

        jLabel15.setText("/");

        buttonGroup1.add(laki);
        laki.setText("Laki-Laki");

        buttonGroup1.add(bini);
        bini.setText("Perempuan");
        bini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biniActionPerformed(evt);
            }
        });

        pilihan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Islam", "Kristen", "Hindu", "Kong Hu Cu" }));

        statusnya.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kawin", "Belum Kawin", " " }));

        darah.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "AB", "B", "O" }));

        buttonGroup2.add(wni);
        wni.setText("WNI");

        buttonGroup2.add(wna);
        wna.setText("WNA");

        jLabel16.setText("/");

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 2, 24)); // NOI18N
        jLabel1.setText("FORM KARTU TANDA PENDUDUK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama)
                    .addComponent(ttl)
                    .addComponent(jk)
                    .addComponent(almt)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kd)
                            .addComponent(rtrw)
                            .addComponent(kec)
                            .addComponent(kota)))
                    .addComponent(agm)
                    .addComponent(sts)
                    .addComponent(gd)
                    .addComponent(pk)
                    .addComponent(kw))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(wni)
                        .addGap(10, 10, 10)
                        .addComponent(wna))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(darah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(statusnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(namanya)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(tempatnya, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tanggalnya, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addComponent(alamatnya)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(rtnya, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rwnya))
                        .addComponent(desanya)
                        .addComponent(kecamatannya)
                        .addComponent(kotanya)
                        .addComponent(pekerjaanya)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(laki)
                            .addGap(18, 18, 18)
                            .addComponent(bini))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(reset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(register)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama)
                    .addComponent(namanya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempatnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ttl)
                        .addComponent(jLabel15)
                        .addComponent(tanggalnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jk)
                    .addComponent(laki)
                    .addComponent(bini))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(almt)
                    .addComponent(alamatnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtrw)
                    .addComponent(rtnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rwnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kd)
                    .addComponent(desanya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kec)
                    .addComponent(kecamatannya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kota)
                    .addComponent(kotanya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agm)
                    .addComponent(pilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sts)
                    .addComponent(statusnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gd)
                    .addComponent(darah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pk)
                    .addComponent(pekerjaanya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kw)
                    .addComponent(wni)
                    .addComponent(wna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset)
                    .addComponent(register))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void biniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biniActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_biniActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        namanya.setText("");
        tempatnya.setText("");
        tanggalnya.setText("");
        buttonGroup1.clearSelection();
        alamatnya.setText("");
        rtnya.setText("");
        rwnya.setText("");
        desanya.setText("");
        kecamatannya.setText("");
        kotanya.setText("");
        pilihan.setSelectedItem(null);
        statusnya.setSelectedItem(null);
        darah.setSelectedItem(null);
        pekerjaanya.setText("");
        buttonGroup2.clearSelection();
    }//GEN-LAST:event_resetActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        String Nama, ttl, tl, Alamat, RT, RW, desa, Kec, kota, agama, status, godar, pekerjaan;
        Nama = namanya.getText();
        ttl = tempatnya.getText();
        tl = tanggalnya.getText();
        String JK = null;
            if (laki.isSelected())
            {JK = laki.getText();}
            else if (bini.isSelected())
            {JK =bini.getText();}
        Alamat =alamatnya.getText();
        RT = rtnya.getText();
        RW = rwnya.getText();
        desa = desanya.getText();
        Kec = kecamatannya.getText();
        kota = kotanya.getText();
        agama = pilihan.getSelectedItem().toString();
        status = statusnya.getSelectedItem().toString();
        godar = darah.getSelectedItem().toString();
        pekerjaan = pekerjaanya.getText();
        String kewarganegaraan=null;
            if (wni.isSelected())
            {kewarganegaraan = wna.getText();}
            else if (wna.isSelected())
            {kewarganegaraan = wni.getText();}
            
       
       Tugas2_Output x = new Tugas2_Output(Nama, ttl, tl, JK, Alamat, RT, RW, desa, Kec, kota, agama, status, godar, pekerjaan, kewarganegaraan);
        x.setVisible(true);
             
    }//GEN-LAST:event_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agm;
    private javax.swing.JTextField alamatnya;
    private javax.swing.JLabel almt;
    private javax.swing.JRadioButton bini;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> darah;
    private javax.swing.JTextField desanya;
    private javax.swing.JLabel gd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jk;
    private javax.swing.JLabel kd;
    private javax.swing.JLabel kec;
    private javax.swing.JTextField kecamatannya;
    private javax.swing.JLabel kota;
    private javax.swing.JTextField kotanya;
    private javax.swing.JLabel kw;
    private javax.swing.JRadioButton laki;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField namanya;
    private javax.swing.JTextField pekerjaanya;
    private javax.swing.JComboBox<String> pilihan;
    private javax.swing.JLabel pk;
    private javax.swing.JButton register;
    private javax.swing.JButton reset;
    private javax.swing.JTextField rtnya;
    private javax.swing.JLabel rtrw;
    private javax.swing.JTextField rwnya;
    private javax.swing.JComboBox<String> statusnya;
    private javax.swing.JLabel sts;
    private javax.swing.JTextField tanggalnya;
    private javax.swing.JTextField tempatnya;
    private javax.swing.JLabel ttl;
    private javax.swing.JRadioButton wna;
    private javax.swing.JRadioButton wni;
    // End of variables declaration//GEN-END:variables
}
