/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas3;

/**
 *
 * @author HeryAdityaa
 */
public class Tugas3 extends javax.swing.JFrame { 

    /**
     * Creates new form latihan
     */
    public Tugas3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelhome = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelktp = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        ttl = new javax.swing.JLabel();
        jk = new javax.swing.JLabel();
        almt = new javax.swing.JLabel();
        rr = new javax.swing.JLabel();
        kd = new javax.swing.JLabel();
        kec = new javax.swing.JLabel();
        kota = new javax.swing.JLabel();
        agm = new javax.swing.JLabel();
        sts = new javax.swing.JLabel();
        gd = new javax.swing.JLabel();
        pk = new javax.swing.JLabel();
        kw = new javax.swing.JLabel();
        namanya = new javax.swing.JTextField();
        tempatnya = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tanggalnya = new javax.swing.JTextField();
        laki = new javax.swing.JRadioButton();
        bini = new javax.swing.JRadioButton();
        alamatnya = new javax.swing.JTextField();
        rtnya = new javax.swing.JTextField();
        rwnya = new javax.swing.JTextField();
        desanya = new javax.swing.JTextField();
        kecamatannya = new javax.swing.JTextField();
        kotanya = new javax.swing.JTextField();
        pilihan = new javax.swing.JComboBox<String>();
        statusnya = new javax.swing.JComboBox<String>();
        darahnya = new javax.swing.JComboBox<String>();
        pekerjannya = new javax.swing.JTextField();
        wni = new javax.swing.JRadioButton();
        wna = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        breset = new javax.swing.JButton();
        bregister = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelkt = new javax.swing.JPanel();
        nama2 = new javax.swing.JLabel();
        ttl2 = new javax.swing.JLabel();
        jk2 = new javax.swing.JLabel();
        almt2 = new javax.swing.JLabel();
        rr2 = new javax.swing.JLabel();
        kd2 = new javax.swing.JLabel();
        kec2 = new javax.swing.JLabel();
        kota2 = new javax.swing.JLabel();
        agm2 = new javax.swing.JLabel();
        sts2 = new javax.swing.JLabel();
        gd2 = new javax.swing.JLabel();
        pk2 = new javax.swing.JLabel();
        kw2 = new javax.swing.JLabel();
        namanyaa = new javax.swing.JTextField();
        tempatnyaa = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tanggalnyaa = new javax.swing.JTextField();
        alamatnyaa = new javax.swing.JTextField();
        rtnyaa = new javax.swing.JTextField();
        rwnyaa = new javax.swing.JTextField();
        desanyaa = new javax.swing.JTextField();
        kecamatannyaa = new javax.swing.JTextField();
        kotanyaa = new javax.swing.JTextField();
        pekerjannyaa = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        kewarganegaraannyaa = new javax.swing.JTextField();
        darahnyaa = new javax.swing.JTextField();
        agamanyaa = new javax.swing.JTextField();
        statusnyaa = new javax.swing.JTextField();
        jknyaa = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jMenu12.setText("jMenu12");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setLayout(new java.awt.CardLayout());

        panelhome.setBackground(new java.awt.Color(255, 255, 102));

        jLabel8.setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setFont(new java.awt.Font("Mangal", 1, 24)); // NOI18N
        jLabel1.setText("SELAMAT DATANG");

        jLabel5.setFont(new java.awt.Font("Mangal", 1, 24)); // NOI18N
        jLabel5.setText("DINAS KEPENDUDUKAN & CATATAN SIPIL KUTAI TIMUR");

        javax.swing.GroupLayout panelhomeLayout = new javax.swing.GroupLayout(panelhome);
        panelhome.setLayout(panelhomeLayout);
        panelhomeLayout.setHorizontalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhomeLayout.createSequentialGroup()
                .addGroup(panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelhomeLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel8))
                    .addGroup(panelhomeLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelhomeLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel5)))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        panelhomeLayout.setVerticalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhomeLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(414, Short.MAX_VALUE))
        );

        jPanel1.add(panelhome, "card2");

        panelktp.setBackground(new java.awt.Color(102, 255, 255));

        nama.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama.setText("Nama");

        ttl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ttl.setText("Tempat/Tanggal Lahir");

        jk.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jk.setText("Jenis Kelamin");

        almt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        almt.setText("Alamat");

        rr.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rr.setText("RT/RW");

        kd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kd.setText("Kel/Desa");

        kec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kec.setText("Kecamatan");

        kota.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kota.setText("Kota");

        agm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        agm.setText("Agama");

        sts.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sts.setText("Status");

        gd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gd.setText("Golongan Darah");

        pk.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pk.setText("Pekerjaan");

        kw.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kw.setText("Kewarganeraan");

        jLabel15.setText("/");

        buttonGroup1.add(laki);
        laki.setText("Laki-Laki");

        buttonGroup1.add(bini);
        bini.setText("Perempuan");
        bini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biniActionPerformed(evt);
            }
        });

        pilihan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Islam", "Kristen", "Hindu", "Kong Hu Cu" }));

        statusnya.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kawin", "Belum Kawin", " " }));

        darahnya.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "AB", "B", "O" }));

        buttonGroup2.add(wni);
        wni.setText("WNI");

        buttonGroup2.add(wna);
        wna.setText("WNA");

        jLabel16.setText("/");

        breset.setText("RESET");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });

        bregister.setText("REGISTER");
        bregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregisterActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 153));

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 2, 24)); // NOI18N
        jLabel7.setText("FORM KARTU TANDA PENDUDUK");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelktpLayout = new javax.swing.GroupLayout(panelktp);
        panelktp.setLayout(panelktpLayout);
        panelktpLayout.setHorizontalGroup(
            panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelktpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(breset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bregister)
                .addGap(35, 35, 35))
            .addGroup(panelktpLayout.createSequentialGroup()
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelktpLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama)
                            .addComponent(ttl)
                            .addComponent(jk)
                            .addComponent(almt)
                            .addGroup(panelktpLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kd)
                                    .addComponent(rr)
                                    .addComponent(kec)
                                    .addComponent(kota)))
                            .addComponent(agm)
                            .addComponent(sts)
                            .addComponent(gd)
                            .addComponent(pk)
                            .addComponent(kw))
                        .addGap(26, 26, 26)
                        .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelktpLayout.createSequentialGroup()
                                .addComponent(wni)
                                .addGap(10, 10, 10)
                                .addComponent(wna))
                            .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(darahnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(statusnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(namanya)
                                .addGroup(panelktpLayout.createSequentialGroup()
                                    .addComponent(tempatnya, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tanggalnya, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                                .addComponent(alamatnya)
                                .addGroup(panelktpLayout.createSequentialGroup()
                                    .addComponent(rtnya, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rwnya))
                                .addComponent(desanya)
                                .addComponent(kecamatannya)
                                .addComponent(kotanya)
                                .addComponent(pekerjannya)
                                .addGroup(panelktpLayout.createSequentialGroup()
                                    .addComponent(laki)
                                    .addGap(18, 18, 18)
                                    .addComponent(bini)))))
                    .addGroup(panelktpLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 460, Short.MAX_VALUE))
        );
        panelktpLayout.setVerticalGroup(
            panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelktpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama)
                    .addComponent(namanya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempatnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ttl)
                        .addComponent(jLabel15)
                        .addComponent(tanggalnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jk)
                    .addComponent(laki)
                    .addComponent(bini))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(almt)
                    .addComponent(alamatnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rr)
                    .addComponent(rtnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rwnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kd)
                    .addComponent(desanya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kec)
                    .addComponent(kecamatannya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kota)
                    .addComponent(kotanya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agm)
                    .addComponent(pilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sts)
                    .addComponent(statusnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gd)
                    .addComponent(darahnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pk)
                    .addComponent(pekerjannya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kw)
                    .addComponent(wni)
                    .addComponent(wna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breset)
                    .addComponent(bregister))
                .addGap(54, 54, 54))
        );

        jPanel1.add(panelktp, "card3");

        panelkt.setBackground(new java.awt.Color(102, 255, 255));

        nama2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama2.setText("Nama");

        ttl2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ttl2.setText("Tempat/Tanggal Lahir");

        jk2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jk2.setText("Jenis Kelamin");

        almt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        almt2.setText("Alamat");

        rr2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rr2.setText("RT/RW");

        kd2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kd2.setText("Kel/Desa");

        kec2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kec2.setText("Kecamatan");

        kota2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kota2.setText("Kota");

        agm2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        agm2.setText("Agama");

        sts2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sts2.setText("Status");

        gd2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gd2.setText("Golongan Darah");

        pk2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pk2.setText("Pekerjaan");

        kw2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kw2.setText("Kewarganeraan");

        namanyaa.setEditable(false);

        tempatnyaa.setEditable(false);

        jLabel17.setText("/");

        tanggalnyaa.setEditable(false);

        alamatnyaa.setEditable(false);

        rtnyaa.setEditable(false);

        rwnyaa.setEditable(false);

        desanyaa.setEditable(false);

        kecamatannyaa.setEditable(false);
        kecamatannyaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kecamatannyaaActionPerformed(evt);
            }
        });

        kotanyaa.setEditable(false);

        pekerjannyaa.setEditable(false);

        jLabel18.setText("/");

        kewarganegaraannyaa.setEditable(false);

        darahnyaa.setEditable(false);

        agamanyaa.setEditable(false);

        statusnyaa.setEditable(false);

        jknyaa.setEditable(false);

        jPanel6.setBackground(new java.awt.Color(255, 255, 153));

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 2, 24)); // NOI18N
        jLabel6.setText("FORM KARTU TANDA PENDUDUK");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(39, 39, 39))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelktLayout = new javax.swing.GroupLayout(panelkt);
        panelkt.setLayout(panelktLayout);
        panelktLayout.setHorizontalGroup(
            panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelktLayout.createSequentialGroup()
                .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelktLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama2)
                            .addComponent(ttl2)
                            .addComponent(jk2)
                            .addComponent(almt2)
                            .addGroup(panelktLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kd2)
                                    .addComponent(rr2)
                                    .addComponent(kec2)
                                    .addComponent(kota2)))
                            .addComponent(agm2)
                            .addComponent(sts2)
                            .addComponent(gd2)
                            .addComponent(pk2)
                            .addComponent(kw2))
                        .addGap(26, 26, 26)
                        .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namanyaa)
                            .addGroup(panelktLayout.createSequentialGroup()
                                .addComponent(tempatnyaa, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tanggalnyaa, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                            .addComponent(alamatnyaa)
                            .addGroup(panelktLayout.createSequentialGroup()
                                .addComponent(rtnyaa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rwnyaa))
                            .addComponent(desanyaa)
                            .addComponent(kecamatannyaa)
                            .addComponent(kotanyaa)
                            .addComponent(pekerjannyaa)
                            .addComponent(kewarganegaraannyaa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(darahnyaa)
                            .addComponent(agamanyaa)
                            .addComponent(statusnyaa)
                            .addComponent(jknyaa)))
                    .addGroup(panelktLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(469, Short.MAX_VALUE))
        );
        panelktLayout.setVerticalGroup(
            panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelktLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama2)
                    .addComponent(namanyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempatnyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ttl2)
                        .addComponent(jLabel17)
                        .addComponent(tanggalnyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jk2)
                    .addComponent(jknyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(almt2)
                    .addComponent(alamatnyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rr2)
                    .addComponent(rtnyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rwnyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kd2)
                    .addComponent(desanyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kec2)
                    .addComponent(kecamatannyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kota2)
                    .addComponent(kotanyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agm2)
                    .addComponent(agamanyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sts2)
                    .addComponent(statusnyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gd2)
                    .addComponent(darahnyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pk2)
                    .addComponent(pekerjannyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kw2)
                    .addComponent(kewarganegaraannyaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jPanel1.add(panelkt, "card4");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("KABUPATEN KUTAI TIMUR");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("DINAS KEPENDUDUKAN & CATATAN SIPIL");

        jPanel5.setLayout(new java.awt.GridLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon("E:\\hery.png")); // NOI18N
        jLabel9.setText("jLabel9");

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("FORM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(511, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1065, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void biniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biniActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        // TODO add your handling code here:
        namanya.setText(""); //set untuk mengatur variable namanya
        tempatnya.setText("");//set untuk mengatur variable tempatnya
        tanggalnya.setText("");
        buttonGroup1.clearSelection();  //untuk memilih pada jenis kelaminnya
        alamatnya.setText("");//set untuk mengatur variable alamatnya
        rtnya.setText("");//set untuk mengatur variable rtnya
        rwnya.setText("");
        desanya.setText("");
        kecamatannya.setText("");
        kotanya.setText("");
        pilihan.setSelectedItem(null); //untuk memilih panel agama dan apabila tidak memilih maka akan null hasilnya
        statusnya.setSelectedItem(null);//untuk memilih statusnya
        darahnya.setSelectedItem(null);//untuk memilih pilihan darahnyaa
        pekerjannya.setText("");
        buttonGroup2.clearSelection();
        
        
    }//GEN-LAST:event_bresetActionPerformed

    private void bregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregisterActionPerformed
        // TODO add your handling code here:
        namanyaa.setText(this.namanya.getText()); //disini menggunakan get, dimana get berfungsi untuk mengambil nilai dari nama yang sudah di isi tadii
        tempatnyaa.setText(this.tempatnya.getText());//sama seprti diatas menggunakan fungsi get untuk mengambil/menampilkan nama tempat ynag sudah kita isi dari set tadi
        tanggalnyaa.setText(this.tanggalnya.getText());
        if (laki.isSelected()) {              //pilihan jika memilih laki-laki maka
            jknyaa.setText(laki.getText());      //akan terpilih laki-laki dan menampilkannya
        }
        else if (bini.isSelected()) {            //jika memilih perrempuan maka akan terpilih perempuan
            jknyaa.setText(bini.getText());         //tidak bisa terpilih keduanya karena diberi seleksi kondisi if dan else, dan pada bagian design sudah diberi buttonGroup
        }                                        //dimana fungsinya buttonGroup agar tidak dapat dippilih kedua2nya sekaligus
        alamatnyaa.setText(this.alamatnya.getText());//sama seperti yang lainnya disni diberikan fungsi set dan get
        rtnyaa.setText(this.rtnya.getText());
        rwnyaa.setText(this.rwnya.getText());
        desanyaa.setText(this.desanya.getText());
        kecamatannyaa.setText(this.kecamatannya.getText());
        kotanyaa.setText(this.kotanya.getText());
        agamanyaa.setText(this.pilihan.getSelectedItem().toString()); //disni ada fungsi getselected karena pilihan pada agama disni menggunakan combobox
        statusnyaa.setText(this.statusnya.getSelectedItem().toString());
        darahnyaa.setText(this.darahnya.getSelectedItem().toString());
        pekerjannyaa.setText(this.pekerjannya.getText());
        if (wni.isSelected()) {
            kewarganegaraannyaa.setText(wna.getText());
        }
        else if (wna.isSelected()) {
            kewarganegaraannyaa.setText(wni.getText());
        }
        
        
        
        
        
        /*String Nama, ttl, tl, Alamat, RT, RW, desa, Kec, kota, agama, status, godar, pekerjaan;
        Nama = jtnama.getText();
        ttl = jtttl1.getText();
        tl = jtttl2.getText();
        String JK = null;
        if (rblaki.isSelected())
        {JK = rblaki.getText();}
        else if (rbp.isSelected())
        {JK =rbp.getText();}
        Alamat =jtalmt.getText();
        RT = jtr1.getText();
        RW = jtr2.getText();
        desa = jtkd.getText();
        Kec = jtkec.getText();
        kota = jtkota.getText();
        agama = cbagm.getSelectedItem().toString();
        status = cbsts.getSelectedItem().toString();
        godar = cbgd.getSelectedItem().toString();
        pekerjaan = jtpek.getText();
        String kewarganegaraan=null;
        if (rbkew1.isSelected())
        {kewarganegaraan = rbkew2.getText();}
        else if (rbkew2.isSelected())
        {kewarganegaraan = rbkew1.getText();}

        //panelktp2 x = new panelktp2(Nama, ttl, tl, JK, Alamat, RT, RW, desa, Kec, kota, agama, status, godar, pekerjaan, kewarganegaraan);
        x.setVisible(true);*/
        panelkt.setVisible(true); //apabila panelktp2 true maka yang muncul panel ktp 
        panelktp.setVisible(false);//apabila panelktp false maka yang muncul panel yang true
    }//GEN-LAST:event_bregisterActionPerformed

    private void kecamatannyaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kecamatannyaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kecamatannyaaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panelhome.setVisible(true);
        panelktp.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        panelktp.setVisible(true);
        panelhome.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit (0); //untuk mengakhiri program
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agamanyaa;
    private javax.swing.JLabel agm;
    private javax.swing.JLabel agm2;
    private javax.swing.JTextField alamatnya;
    private javax.swing.JTextField alamatnyaa;
    private javax.swing.JLabel almt;
    private javax.swing.JLabel almt2;
    private javax.swing.JRadioButton bini;
    private javax.swing.JButton bregister;
    private javax.swing.JButton breset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> darahnya;
    private javax.swing.JTextField darahnyaa;
    private javax.swing.JTextField desanya;
    private javax.swing.JTextField desanyaa;
    private javax.swing.JLabel gd;
    private javax.swing.JLabel gd2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jk;
    private javax.swing.JLabel jk2;
    private javax.swing.JTextField jknyaa;
    private javax.swing.JLabel kd;
    private javax.swing.JLabel kd2;
    private javax.swing.JLabel kec;
    private javax.swing.JLabel kec2;
    private javax.swing.JTextField kecamatannya;
    private javax.swing.JTextField kecamatannyaa;
    private javax.swing.JTextField kewarganegaraannyaa;
    private javax.swing.JLabel kota;
    private javax.swing.JLabel kota2;
    private javax.swing.JTextField kotanya;
    private javax.swing.JTextField kotanyaa;
    private javax.swing.JLabel kw;
    private javax.swing.JLabel kw2;
    private javax.swing.JRadioButton laki;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nama2;
    private javax.swing.JTextField namanya;
    private javax.swing.JTextField namanyaa;
    private javax.swing.JPanel panelhome;
    private javax.swing.JPanel panelkt;
    private javax.swing.JPanel panelktp;
    private javax.swing.JTextField pekerjannya;
    private javax.swing.JTextField pekerjannyaa;
    private javax.swing.JComboBox<String> pilihan;
    private javax.swing.JLabel pk;
    private javax.swing.JLabel pk2;
    private javax.swing.JLabel rr;
    private javax.swing.JLabel rr2;
    private javax.swing.JTextField rtnya;
    private javax.swing.JTextField rtnyaa;
    private javax.swing.JTextField rwnya;
    private javax.swing.JTextField rwnyaa;
    private javax.swing.JComboBox<String> statusnya;
    private javax.swing.JTextField statusnyaa;
    private javax.swing.JLabel sts;
    private javax.swing.JLabel sts2;
    private javax.swing.JTextField tanggalnya;
    private javax.swing.JTextField tanggalnyaa;
    private javax.swing.JTextField tempatnya;
    private javax.swing.JTextField tempatnyaa;
    private javax.swing.JLabel ttl;
    private javax.swing.JLabel ttl2;
    private javax.swing.JRadioButton wna;
    private javax.swing.JRadioButton wni;
    // End of variables declaration//GEN-END:variables
}
